spring.application.name=bleep-learnhub-backend


# --- PostgreSQL Configuration ---
# Use the service name 'db' as the hostname

# spring.datasource.url=jdbc:postgresql://db:5432/learnhub_db
# spring.datasource.username=myuser
# spring.datasource.password=mypassword
spring.datasource.url=jdbc:postgresql://localhost:5433/learnhub_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

# JPA configuration (optional but recommended for development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Redis Configuration ---
# Use the service name 'redis' as the hostname

# spring.data.redis.host=redis
# spring.data.redis.port=6379
# spring.data.redis.password=yourredispassword
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=yourredispassword