spring.application.name=bleep-learnhub-backend


# --- PostgreSQL Configuration ---
# Use the service name 'db' as the hostname

# spring.datasource.url=jdbc:postgresql://db:5432/learnhub_db
# spring.datasource.username=myuser
# spring.datasource.password=mypassword
spring.datasource.url=jdbc:postgresql://localhost:5433/learnhub_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

# JPA configuration (optional but recommended for development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Redis Configuration ---
# Use the service name 'redis' as the hostname

# spring.data.redis.host=redis
# spring.data.redis.port=6379
# spring.data.redis.password=yourredispassword
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=yourredispassword




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=workemail9862@gmail.com
spring.mail.password=Work9862@Niladri@2001



# spring.mail.host: smtp-relay.brevo.com
# spring.mail.port: 587
# spring.mail.username: your_brevo_registered_email
# pring.mail.password: your_brevo_smtp_key

# --- Security / JWT Configuration ---
application.security.jwt.secret-key=U2VjdXJlS2V5Rm9yQmxjZXBMZWFybkh1YkJhY2tlbmRXaXRoU3VmZmljaWVudExlbmd0aE9mQnl0ZXM=
application.security.jwt.expiration=86400000